# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---

name: vulture

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  vulture:
    name: Dead-Code Detection
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docopt vulture

      - name: Run Vulture scan
        run: |
          # Make metrics directory if it doesn't exist
          mkdir -p metrics
          chmod +x metrics/vulture
          ./metrics/vulture

      - name: Check report
        run: |
          if grep -q "[^[:space:]]" vulture_report.txt; then
            echo "::error::Dead code detected:"
            cat vulture_report.txt
            exit 1
          else
            echo "No dead code found"
          fi